2012-07-01 22:38:31 [66916] [INFO] Starting gunicorn 0.14.5
2012-07-01 22:38:31 [66916] [DEBUG] Arbiter booted
2012-07-01 22:38:31 [66916] [INFO] Listening at: http://127.0.0.1:8000 (66916)
2012-07-01 22:38:31 [66916] [INFO] Using worker: sync
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_manager(settings)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/management/commands/run_gunicorn.py", line 100, in handle
    DjangoApplicationCommand(options, admin_media_path).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/app/base.py", line 124, in run
    Arbiter(self).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 157, in run
    self.manage_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 434, in manage_workers
    self.spawn_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 486, in spawn_workers
    self.spawn_worker()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 446, in spawn_worker
    self.cfg, self.log)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/base.py", line 49, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/workertmp.py", line 18, in __init__
    util.chown(name, cfg.uid, cfg.gid)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/util.py", line 154, in chown
    os.chown(path, uid, gid)
OSError: [Errno 1] Operation not permitted: '/var/folders/f7/zypv42zs62l0_26hr2ks32nm0000gn/T/wgunicorn-tjvWw8'
2012-07-01 22:38:36 [66952] [INFO] Starting gunicorn 0.14.5
2012-07-01 22:38:36 [66952] [DEBUG] Arbiter booted
2012-07-01 22:38:36 [66952] [INFO] Listening at: http://127.0.0.1:8000 (66952)
2012-07-01 22:38:36 [66952] [INFO] Using worker: sync
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_manager(settings)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/management/commands/run_gunicorn.py", line 100, in handle
    DjangoApplicationCommand(options, admin_media_path).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/app/base.py", line 124, in run
    Arbiter(self).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 157, in run
    self.manage_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 434, in manage_workers
    self.spawn_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 486, in spawn_workers
    self.spawn_worker()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 446, in spawn_worker
    self.cfg, self.log)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/base.py", line 49, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/workertmp.py", line 18, in __init__
    util.chown(name, cfg.uid, cfg.gid)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/util.py", line 154, in chown
    os.chown(path, uid, gid)
OSError: [Errno 1] Operation not permitted: '/var/folders/f7/zypv42zs62l0_26hr2ks32nm0000gn/T/wgunicorn-2E7FO5'
2012-07-01 22:39:01 [66964] [INFO] Starting gunicorn 0.14.5
2012-07-01 22:39:01 [66964] [DEBUG] Arbiter booted
2012-07-01 22:39:01 [66964] [INFO] Listening at: http://127.0.0.1:8000 (66964)
2012-07-01 22:39:01 [66964] [INFO] Using worker: sync
Traceback (most recent call last):
  File "manage.py", line 20, in <module>
    execute_manager(settings)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 459, in execute_manager
    utility.execute()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/management/commands/run_gunicorn.py", line 100, in handle
    DjangoApplicationCommand(options, admin_media_path).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/app/base.py", line 124, in run
    Arbiter(self).run()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 157, in run
    self.manage_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 434, in manage_workers
    self.spawn_workers()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 486, in spawn_workers
    self.spawn_worker()
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/arbiter.py", line 446, in spawn_worker
    self.cfg, self.log)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/base.py", line 49, in __init__
    self.tmp = WorkerTmp(cfg)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/workers/workertmp.py", line 18, in __init__
    util.chown(name, cfg.uid, cfg.gid)
  File "/Users/cwiz/Envs/food/lib/python2.7/site-packages/gunicorn/util.py", line 154, in chown
    os.chown(path, uid, gid)
OSError: [Errno 1] Operation not permitted: '/var/folders/f7/zypv42zs62l0_26hr2ks32nm0000gn/T/wgunicorn-SUVKEx'
2012-07-01 22:39:13 [66967] [INFO] Starting gunicorn 0.14.5
2012-07-01 22:39:13 [66967] [DEBUG] Arbiter booted
2012-07-01 22:39:13 [66967] [INFO] Listening at: http://127.0.0.1:8000 (66967)
2012-07-01 22:39:13 [66967] [INFO] Using worker: sync
2012-07-01 22:39:13 [66968] [INFO] Booting worker with pid: 66968
2012-07-01 22:39:13 [66969] [INFO] Booting worker with pid: 66969
2012-07-01 22:39:13 [66970] [INFO] Booting worker with pid: 66970
2012-07-01 22:39:17 [66968] [INFO] Worker exiting (pid: 66968)
2012-07-01 22:39:17 [66970] [INFO] Worker exiting (pid: 66970)
2012-07-01 22:39:17 [66969] [INFO] Worker exiting (pid: 66969)
2012-07-01 22:39:17 [66967] [INFO] Handling signal: int
2012-07-01 22:39:17 [66967] [INFO] Shutting down: Master

Error: No such user: 'cwiz--log-level=debug'
2012-07-01 22:40:13 [66992] [INFO] Starting gunicorn 0.14.5
2012-07-01 22:40:13 [66992] [DEBUG] Arbiter booted
2012-07-01 22:40:13 [66992] [INFO] Listening at: http://127.0.0.1:8000 (66992)
2012-07-01 22:40:13 [66992] [INFO] Using worker: sync
2012-07-01 22:40:13 [66994] [INFO] Booting worker with pid: 66994
2012-07-01 22:40:13 [66995] [INFO] Booting worker with pid: 66995
2012-07-01 22:40:13 [66996] [INFO] Booting worker with pid: 66996
2012-07-01 22:40:22 [66996] [INFO] Worker exiting (pid: 66996)
2012-07-01 22:40:22 [66995] [INFO] Worker exiting (pid: 66995)
2012-07-01 22:40:22 [66994] [INFO] Worker exiting (pid: 66994)
2012-07-01 22:40:22 [66992] [INFO] Handling signal: int
2012-07-01 22:40:22 [66992] [INFO] Shutting down: Master
